# Generated by Django 4.2.11 on 2024-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climwebwdqms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='expected',
            field=models.IntegerField(null=True, verbose_name='Transmissions expected'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='received',
            field=models.IntegerField(null=True, verbose_name='Transmissions received'),
        ),
    ]
