# Generated by Django 4.2.11 on 2024-05-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climwebwdqms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Station name'),
        ),
    ]
