# Generated by Django 4.2.11 on 2024-05-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climwebwdqms', '0002_transmission_expected_transmission_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='received_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Transmission Rate'),
        ),
    ]
